version: '3.1'
services:
  strapi:
    image: strapi/strapi:alpine
    restart: always
    container_name: strap
    network_mode: ng
    ports:
      - 1337:1337
    volumes:
      - ./:/srv/app
    env_file: .env
